#Status: Work In Progress

on:
  workflow_call:
    inputs:
      RG:
        required: true
        type: string
      AKSNAME:
        required: true
        type: string
      APPNAME:
        required: true
        type: string
      NAMESPACE:
        default: "default"
        required: false
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  App_Create:
    runs-on: ubuntu-latest
    env:
      APPNAME: "${{ inputs.APPNAME }}"
      NAMESP: "${{ inputs.NAMESPACE }}"
      AKSNAME: "${{ inputs.AKSNAME}}"
      RG: "${{ inputs.RG }}"
      
    steps:
      - uses: actions/checkout@v2

      - name: Job parameter inspection
        run: |
          echo "RG is ${{ inputs.RG }}"
          echo "AKS name is ${{ inputs.AKSNAME }}"
          
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false
          environment: azurecloud
          allow-no-subscriptions: false
      
      - name: Set the target Azure Kubernetes Service (AKS) cluster.
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ inputs.AKSNAME }}
          resource-group: ${{ inputs.RG }}

      - name: Deploy app to AKS
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            https://github.com/Azure/aks-baseline-automation/raw/gb-builtinactions-azurevote/workloads/azure-vote/back-deployment.yml
            https://github.com/Azure/aks-baseline-automation/raw/gb-builtinactions-azurevote/workloads/azure-vote/back-service.yml
            https://github.com/Azure/aks-baseline-automation/raw/gb-builtinactions-azurevote/workloads/azure-vote/front-deployment.yml
            https://github.com/Azure/aks-baseline-automation/raw/gb-builtinactions-azurevote/workloads/azure-vote/front-service.yml
          images: |
            mcr.microsoft.com/azuredocs/azure-vote-front:v1
          namespace: ${{ inputs.NAMESPACE }}
