# Workflow is for testing reusable workflows to expedite the developer inner loop.

name: Test Harness for Reusable App workflows

on:
  workflow_dispatch:
    inputs:
      ResourceGroup:
        description: 'Resource Group Name'
        type: string
        required: true
      AKSNAME:
        description: 'AKS Cluster Name'
        type: string
        required: true
      ACRNAME:
        required: true
        type: string

jobs:
  ReusableWF:
    runs-on: ubuntu-latest
    outputs:
      RG: ${{ github.event.inputs.ResourceGroup }}
      AKSNAME: ${{ github.event.inputs.AKSNAME }}
      ACRNAME: ${{ github.event.inputs.ACRNAME }}

    steps:
      - name: Dummy step
        run: echo "Resuable workflows can't be directly reference ENV/INPUTS (yet)"

  AzureVoteApp:
    needs: [ReusableWF]
    uses: ./.github/workflows/App-AzureVote-BuildOnACR-Actions.yml
    with:
      RG: ${{ needs.ReusableWF.outputs.RG }}
      AKSNAME: ${{ needs.ReusableWF.outputs.AKSNAME }}
      ACRNAME: ${{ needs.ReusableWF.outputs.ACRNAME }}
      APPNAME: basevote1
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
